export type { Category } from "./products";
import type { Category } from "./products";

// The seven categories shown in the section 2 scroll strip, in display
// order. Images for cakes and meat-pies are temporary crops taken from
// the hero video frame, same as the supplied assets; cupcakes, waffles,
// parfaits, banana bread and milky yoghurt are illustrated placeholders
// pending real product photography, generated by scripts/make-placeholders.mjs.
export const categories: Category[] = [
  {
    slug: "cakes",
    name: "Cakes",
    image: "/products/cakes.jpg",
    blurb: "Celebration cakes, layered and finished by hand.",
    order: 1,
  },
  {
    slug: "cupcakes",
    name: "Cupcakes",
    image: "/products/cupcakes.jpg",
    blurb: "Single treats or boxed for sharing.",
    order: 2,
  },
  {
    slug: "parfaits",
    name: "Parfaits",
    image: "/products/parfaits.jpg",
    blurb: "Layered fruit, cream and crunch.",
    order: 3,
  },
  {
    slug: "waffles",
    name: "Waffles",
    image: "/products/waffles.jpg",
    blurb: "Warm, golden, made to order.",
    order: 4,
  },
  {
    slug: "meat-pies",
    name: "Meat Pies",
    image: "/products/meat-pies.jpg",
    blurb: "Flaky pastry, savoury filling.",
    order: 5,
  },
  {
    slug: "banana-bread",
    name: "Banana Bread",
    image: "/products/banana-bread.jpg",
    blurb: "Moist, dense, and just sweet enough.",
    order: 6,
  },
  {
    slug: "milky-yoghurt",
    name: "Milky Yoghurt",
    image: "/products/milky-yoghurt.jpg",
    blurb: "Cool, creamy, and refreshing.",
    order: 7,
  },
];

// The full menu page sidebar shows more categories than the homepage
// strip does. Same 7 above, plus three more the homepage never surfaces.
export const menuCategories: Category[] = [
  ...categories,
  {
    slug: "greek-yoghurt",
    name: "Greek Yoghurt",
    image: "/products/greek-yoghurt.jpg",
    blurb: "Thick, tangy, and protein-rich.",
    order: 8,
  },
  {
    slug: "small-chops",
    name: "Small Chops",
    image: "/products/small-chops.jpg",
    blurb: "A mixed tray for sharing.",
    order: 9,
  },
  {
    slug: "granola",
    name: "Granola",
    image: "/products/granola.jpg",
    blurb: "Toasted, honeyed, and crunchy.",
    order: 10,
  },
];
