import type { Category } from "./products";

// The seven categories shown in the section 2 scroll strip, in display
// order. Images for cakes and meat-pies are temporary crops taken from
// the hero video frame, same as the supplied assets; cupcakes, waffles,
// parfaits, banana bread and milky yoghurt are illustrated placeholders
// pending real product photography, generated by scripts/make-placeholders.mjs.
export const categories: Category[] = [
  {
    slug: "cakes",
    name: "Cakes",
    image: "/products/cakes.jpg",
    blurb: "Celebration cakes, layered and finished by hand.",
    order: 1,
  },
  {
    slug: "cupcakes",
    name: "Cupcakes",
    image: "/products/cupcakes.jpg",
    blurb: "Single treats or boxed for sharing.",
    order: 2,
  },
  {
    slug: "parfaits",
    name: "Parfaits",
    image: "/products/parfaits.jpg",
    blurb: "Layered fruit, cream and crunch.",
    order: 3,
  },
  {
    slug: "waffles",
    name: "Waffles",
    image: "/products/waffles.jpg",
    blurb: "Warm, golden, made to order.",
    order: 4,
  },
  {
    slug: "meat-pies",
    name: "Meat Pies",
    image: "/products/meat-pies.jpg",
    blurb: "Flaky pastry, savoury filling.",
    order: 5,
  },
  {
    slug: "banana-bread",
    name: "Banana Bread",
    image: "/products/banana-bread.jpg",
    blurb: "Moist, dense, and just sweet enough.",
    order: 6,
  },
  {
    slug: "milky-yoghurt",
    name: "Milky Yoghurt",
    image: "/products/milky-yoghurt.jpg",
    blurb: "Cool, creamy, and refreshing.",
    order: 7,
  },
];
